# Form implementation generated from reading ui file 'project2gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.user_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(190, 10, 421, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setKerning(True)
        self.user_label.setFont(font)
        self.user_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.user_label.setObjectName("user_label")
        self.balance_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.balance_label.setEnabled(True)
        self.balance_label.setGeometry(QtCore.QRect(250, 80, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.balance_label.setFont(font)
        self.balance_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.balance_label.setObjectName("balance_label")
        self.budget_message = QtWidgets.QLabel(parent=self.centralwidget)
        self.budget_message.setGeometry(QtCore.QRect(170, 170, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.budget_message.setFont(font)
        self.budget_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.budget_message.setObjectName("budget_message")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(80, 150, 641, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.income_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.income_radio.setGeometry(QtCore.QRect(280, 210, 95, 20))
        self.income_radio.setObjectName("income_radio")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName("radio_group")
        self.radio_group.addButton(self.income_radio)
        self.expense_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.expense_radio.setGeometry(QtCore.QRect(450, 210, 95, 20))
        self.expense_radio.setObjectName("expense_radio")
        self.radio_group.addButton(self.expense_radio)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 240, 761, 321))
        self.stackedWidget.setObjectName("stackedWidget")
        self.income_page = QtWidgets.QWidget()
        self.income_page.setObjectName("income_page")
        self.howmuchincome_entry = QtWidgets.QLineEdit(parent=self.income_page)
        self.howmuchincome_entry.setGeometry(QtCore.QRect(280, 40, 201, 31))
        self.howmuchincome_entry.setObjectName("howmuchincome_entry")
        self.howmuchincome_label = QtWidgets.QLabel(parent=self.income_page)
        self.howmuchincome_label.setGeometry(QtCore.QRect(280, 20, 201, 20))
        self.howmuchincome_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.howmuchincome_label.setObjectName("howmuchincome_label")
        self.or_label = QtWidgets.QLabel(parent=self.income_page)
        self.or_label.setGeometry(QtCore.QRect(280, 90, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.or_label.setFont(font)
        self.or_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.or_label.setObjectName("or_label")
        self.hourlywage_entry = QtWidgets.QLineEdit(parent=self.income_page)
        self.hourlywage_entry.setGeometry(QtCore.QRect(280, 150, 201, 31))
        self.hourlywage_entry.setObjectName("hourlywage_entry")
        self.hoursworked_entry = QtWidgets.QLineEdit(parent=self.income_page)
        self.hoursworked_entry.setGeometry(QtCore.QRect(280, 210, 201, 31))
        self.hoursworked_entry.setObjectName("hoursworked_entry")
        self.hourlywage_label = QtWidgets.QLabel(parent=self.income_page)
        self.hourlywage_label.setGeometry(QtCore.QRect(280, 130, 201, 20))
        self.hourlywage_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hourlywage_label.setObjectName("hourlywage_label")
        self.hoursworked_label = QtWidgets.QLabel(parent=self.income_page)
        self.hoursworked_label.setGeometry(QtCore.QRect(280, 190, 201, 20))
        self.hoursworked_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.hoursworked_label.setObjectName("hoursworked_label")
        self.submitincome_button = QtWidgets.QPushButton(parent=self.income_page)
        self.submitincome_button.setGeometry(QtCore.QRect(330, 270, 93, 28))
        self.submitincome_button.setObjectName("submitincome_button")
        self.stackedWidget.addWidget(self.income_page)
        self.expense_page = QtWidgets.QWidget()
        self.expense_page.setObjectName("expense_page")
        self.expensetype_dropbox = QtWidgets.QComboBox(parent=self.expense_page)
        self.expensetype_dropbox.setGeometry(QtCore.QRect(260, 50, 231, 22))
        self.expensetype_dropbox.setObjectName("expensetype_dropbox")
        self.expensetype_dropbox.addItem("")
        self.expensetype_dropbox.addItem("")
        self.expensetype_dropbox.addItem("")
        self.expensetype_dropbox.addItem("")
        self.selectexpense_label = QtWidgets.QLabel(parent=self.expense_page)
        self.selectexpense_label.setGeometry(QtCore.QRect(280, 20, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectexpense_label.setFont(font)
        self.selectexpense_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.selectexpense_label.setObjectName("selectexpense_label")
        self.amountofexpense_label = QtWidgets.QLabel(parent=self.expense_page)
        self.amountofexpense_label.setGeometry(QtCore.QRect(230, 90, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.amountofexpense_label.setFont(font)
        self.amountofexpense_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.amountofexpense_label.setObjectName("amountofexpense_label")
        self.amountofexpense_entry = QtWidgets.QLineEdit(parent=self.expense_page)
        self.amountofexpense_entry.setGeometry(QtCore.QRect(250, 130, 261, 41))
        self.amountofexpense_entry.setObjectName("amountofexpense_entry")
        self.expensesubmit_button = QtWidgets.QPushButton(parent=self.expense_page)
        self.expensesubmit_button.setGeometry(QtCore.QRect(330, 190, 93, 28))
        self.expensesubmit_button.setObjectName("expensesubmit_button")
        self.stackedWidget.addWidget(self.expense_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.income_radio.toggled.connect(self.radio_behavior)
        self.expense_radio.toggled.connect(self.radio_behavior)
        self.income_radio.setChecked(True)

        self.hourlywage_entry.textEdited.connect(self.income_fields_behavior)
        self.hoursworked_entry.textEdited.connect(self.income_fields_behavior)
        self.howmuchincome_entry.textEdited.connect(self.income_fields_behavior)

    def radio_behavior(self) -> None:
        """
        This function defines the behavior of the radio buttons
        """
        if self.income_radio.isChecked():
            self.stackedWidget.setCurrentIndex(0)
        elif self.expense_radio.isChecked():
            self.stackedWidget.setCurrentIndex(1)

    def income_fields_behavior(self) -> None:
        """
        This function describes the behavior of the two sets of fields under the "income tab"
        Notably, this prevents a user from being able to type in both sets of fields at the same time
        """
        if self.hourlywage_entry.hasFocus() or self.hoursworked_entry.hasFocus():
            self.howmuchincome_entry.clear()
        elif self.howmuchincome_entry.hasFocus():
            self.hourlywage_entry.clear()
            self.hoursworked_entry.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Budget Tool"))
        self.user_label.setText(_translate("MainWindow", "John Smith\'s Budget"))
        self.balance_label.setText(_translate("MainWindow", "$0.00"))
        self.budget_message.setText(_translate("MainWindow", "Report A Change To Your Budget"))
        self.income_radio.setText(_translate("MainWindow", "Income"))
        self.expense_radio.setText(_translate("MainWindow", "Expense"))
        self.howmuchincome_label.setText(_translate("MainWindow", "Enter A Total Amount"))
        self.or_label.setText(_translate("MainWindow", "Or"))
        self.hourlywage_label.setText(_translate("MainWindow", "Enter An Hourly Wage"))
        self.hoursworked_label.setText(_translate("MainWindow", "Enter Hours Worked"))
        self.submitincome_button.setText(_translate("MainWindow", "Submit"))
        self.expensetype_dropbox.setItemText(0, _translate("MainWindow", "Grocery"))
        self.expensetype_dropbox.setItemText(1, _translate("MainWindow", "Rent"))
        self.expensetype_dropbox.setItemText(2, _translate("MainWindow", "Debt"))
        self.expensetype_dropbox.setItemText(3, _translate("MainWindow", "Other"))
        self.selectexpense_label.setText(_translate("MainWindow", "Select Expense Type"))
        self.amountofexpense_label.setText(_translate("MainWindow", "Enter Amount Of The Expense"))
        self.expensesubmit_button.setText(_translate("MainWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
